#!/usr/bin/env bash
set -ex

cd bootstrap

echo "" > site/_includes/ads.html

npm install

bundle install

npm run docs-compile

mkdir -p ../documentation/docs/4.3/dist/css

cp -R _gh_pages/* ../documentation

cd ..

cp dist/css/uba-bootstrap-theme.css documentation/docs/4.3/dist/css/bootstrap.css
